version: '2'

services:
  redmine-postgresql:
    container_name: redmine-postgresql
    image: sameersbn/postgresql:9.4-4 
#    ports:
#    - "5432:5432"    
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/redmine_data/postgresql:/var/lib/postgresql
    environment:
    - PG_PASSWORD=passw0rd
    - DB_NAME=redmine
    - DB_USER=redmine
    - DB_PASS=redmine
    - TZ=Asia/Taipei
#   network_mode:  "host"
# mac系統無法使用network host
  redmine:
    container_name: redmine303
    image: sameersbn/redmine:3.0.3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/redmine_data/redmine:/home/redmine/data
    environment:
    - REDMINE_RELATIVE_URL_ROOT=/redmine
    - SMTP_USER=iisi.sonar@gmail.com
    - SMTP_PASS=0920301309
    - DB_TYPE=postgres
    - DB_HOST=redmine-postgresql
    - DB_NAME=redmine
    - DB_USER=redmine
    - DB_PASS=redmine
#    - DB_HOST=192.168.57.21
    - TZ=Asia/Taipei
    depends_on:
    - "redmine-postgresql"
#    network_mode:  "host"
    ports: 
    - "10080:80" 
  
